name: Preprocessing Data

on:
  push:
    branches:
      - master
    paths:
      - "mushrooms_raw.csv"

jobs:
  preprocesing_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python Version 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run processing dataset script
      run: |
        python preprocessing/automate_refan.py

    - name: Commit preprocessing dataset
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "GithubActions: updated preprocessed dataset"
        file_pattern: "preprocessing/*"
      

      
      
  

